// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iutdcjmjgwrhdiiicozh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1dGRjam1qZ3dyaGRpaWljb3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzAyMjgsImV4cCI6MjA2NTUwNjIyOH0.GDBa69LcmqojG2KJEht6fSPbD9lFlnRMYW2yA-JIbQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);